import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { SITE } from '@/config/site'
import { COURSES, FRONTIER_LEVELS, GATED_LEVELS, MAX_XP, PRODUCTION_LEVELS, getRank } from '@/data/curriculum'
import { getCompletionSummary, loadProgress } from '@/engine/progress'
import { getDefense, loadReview } from '@/engine/review'
import { renderShareCard } from '@/engine/shareCard'
import { downloadLearningData, resetAllLearningData } from '@/engine/storage'

function completionCode(name:string,label:string,completed:number,xp:number):string{const input=`${name.trim().toLowerCase()}|${label}|${completed}|${xp}`;let h=0x811c9dc5;for(let i=0;i<input.length;i++){h^=input.charCodeAt(i);h=Math.imul(h,0x01000193)>>>0}return h.toString(36).toUpperCase().padStart(7,'0')}
const NAME_KEY='llmquest_name'

export function CertPage(){
  const [name,setName]=useState(()=>{try{return localStorage.getItem(NAME_KEY)??''}catch{return''}})
  const progress=loadProgress(), review=loadReview(), completion=getCompletionSummary(progress), rank=getRank(progress.totalXp)
  const credential=completion.full.done?{label:'Full LLM Engineering',...completion.full,levels:GATED_LEVELS}:completion.production.done?{label:'Production AI Engineering',...completion.production,levels:PRODUCTION_LEVELS}:completion.frontier.done?{label:'Frontier Model Training',...completion.frontier,levels:FRONTIER_LEVELS}:null
  const completedGated=GATED_LEVELS.filter(l=>progress.levels[l.id]?.status==='complete').length
  const percent=Math.round(completedGated/GATED_LEVELS.length*100)
  const dates=(credential?.levels??GATED_LEVELS).map(l=>progress.levels[l.id]?.completedAt).filter((x):x is number=>x!==undefined)
  const finishedOn=dates.length?new Date(Math.max(...dates)).toLocaleDateString('en-US',{year:'numeric',month:'long',day:'numeric'}):''
  const retained=Object.values(review.cards).filter(c=>c.box>=2).length
  function saveName(v:string){setName(v);try{localStorage.setItem(NAME_KEY,v)}catch{}}
  const [cardUrl,setCardUrl]=useState('')
  useEffect(()=>{let cancelled=false;renderShareCard({name:name.trim(),rankTitle:rank.title,rankColor:rank.color,xp:progress.totalXp,completed:credential?.completed??completedGated,total:credential?.total??GATED_LEVELS.length,done:Boolean(credential),code:credential?completionCode(name,credential.label,credential.completed,progress.totalXp):'',siteName:SITE.name,tagline:credential?.label??SITE.tagline,domain:SITE.domain}).then(u=>{if(!cancelled)setCardUrl(u)}).catch(()=>{});return()=>{cancelled=true}},[name,completedGated,progress.totalXp,credential?.label])

  return <div className="min-h-screen bg-gray-950 text-white"><header className="border-b border-gray-800 px-5 sm:px-6 py-4 flex flex-wrap items-center gap-4 print:hidden"><Link to="/map" className="text-gray-500 hover:text-white text-sm font-mono">← Map</Link><h1 className="font-bold text-lg text-violet-500">Certificates & Transcript</h1><div className="ml-auto flex gap-2"><button onClick={downloadLearningData} className="nav-chip">Export progress</button>{credential&&<button onClick={()=>window.print()} className="nav-chip">Print / PDF</button>}</div></header>
  <div className="max-w-2xl mx-auto px-5 sm:px-6 py-8">
    <section className="mb-8 print:hidden"><label htmlFor="cert-name" className="block text-xs font-mono text-gray-500 mb-2">Name as it should appear on a certificate</label><input id="cert-name" value={name} onChange={e=>saveName(e.target.value)} placeholder="Ada Lovelace" className="w-full max-w-sm px-4 py-2.5 rounded-lg bg-gray-900 border border-gray-700 focus:border-violet-500 text-sm"/></section>

    {credential&&name.trim()?<section className="rounded-2xl border-2 border-violet-600 p-8 sm:p-10 text-center mb-10 bg-gray-900/70 print:bg-white print:text-black"><p className="text-xs font-mono uppercase tracking-widest text-violet-400 mb-6">{SITE.name} · Certificate of Completion</p><h2 className="text-3xl font-bold">{name.trim()}</h2><p className="text-gray-400 print:text-gray-700 text-sm mt-2 mb-6">completed the<br/><strong className="text-gray-200 print:text-black">{credential.label} specialization</strong></p><div className="flex flex-wrap justify-center gap-8 text-sm font-mono mb-6"><div><p className="text-gray-500">Levels</p><p className="font-bold">{credential.completed}/{credential.total}</p></div><div><p className="text-gray-500">XP</p><p className="font-bold text-yellow-300 print:text-black">{progress.totalXp.toLocaleString()}</p></div><div><p className="text-gray-500">Date</p><p className="font-bold">{finishedOn}</p></div></div><p className="text-xs font-mono text-gray-600">Completion code: {completionCode(name,credential.label,credential.completed,progress.totalXp)} · {SITE.domain}</p></section>
    :<section className="rounded-2xl border border-gray-800 bg-gray-900/40 p-7 mb-10"><h2 className="text-lg font-semibold">Specialization progress</h2><p className="text-sm text-gray-500 mt-1">Complete either route to earn a certificate. Course 0 is optional.</p><div className="mt-5 space-y-4">{[{name:'Production AI Engineering',x:completion.production},{name:'Frontier Model Training',x:completion.frontier},{name:'Full LLM Engineering',x:completion.full}].map(({name,x})=><div key={name}><div className="flex justify-between text-xs font-mono"><span>{name}</span><span className={x.done?'text-emerald-400':'text-gray-500'}>{x.completed}/{x.total}{x.done?' complete':''}</span></div><div role="progressbar" aria-label={`${name}: ${x.completed} of ${x.total}`} aria-valuemin={0} aria-valuemax={x.total} aria-valuenow={x.completed} className="h-2 rounded-full bg-gray-800 mt-2 overflow-hidden"><div className="h-full bg-violet-600" style={{width:`${Math.round(x.completed/x.total*100)}%`}}/></div></div>)}</div>{!name.trim()&&credential&&<p className="text-amber-300 text-sm mt-4">Enter your name above to issue the certificate.</p>}</section>}

    {cardUrl&&<section className="mb-10 print:hidden"><h2 className="section-label">Share card</h2><img src={cardUrl} alt={`${SITE.name} learning progress card`} className="w-full rounded-xl border border-gray-800 mb-3"/><a href={cardUrl} download="zeroone-card.png" className="nav-chip inline-block">Download PNG</a></section>}

    <section><h2 className="section-label">Mastery transcript</h2><div className="grid gap-2">{COURSES.map(c=>{const done=c.levels.filter(l=>progress.levels[l.id]?.status==='complete').length;const xp=c.levels.reduce((n,l)=>n+(progress.levels[l.id]?.xpEarned??0),0);const d=getDefense(c.id);return <div key={c.id} className="flex items-center gap-4 p-4 rounded-xl border border-gray-800 bg-gray-900/40 print:bg-white"><span className="text-xs font-mono font-semibold w-8" style={{color:c.accent}}>C{c.id}</span><div className="flex-1"><p className="text-sm">{c.title}</p><p className="text-xs text-gray-500 font-mono">{done}/{c.levels.length} levels · {xp.toLocaleString()} XP{d?` · defense ${d.bestPct}%`:''}</p></div><span>{done===c.levels.length?(d&&d.bestPct>=80?'🛡️':'✓'):done>0?'▶':'—'}</span></div>})}</div><p className="text-xs font-mono text-gray-600 mt-5">{progress.totalXp.toLocaleString()} / {MAX_XP.toLocaleString()} available XP{review.xpFromReview?` · +${review.xpFromReview} review XP`:''}{retained?` · ${retained} cards in 7+ day retention`:''}</p></section>

    <section className="mt-14 pt-6 border-t border-gray-900 print:hidden"><h2 className="text-sm font-semibold text-gray-300">Local learning data</h2><p className="text-xs text-gray-600 mt-1 mb-4">Export a backup before restarting. Reset clears coding progress, concept lessons, review history, warm-ups, drafts, and certificate name.</p><div className="flex gap-3"><button onClick={downloadLearningData} className="nav-chip">Export backup</button><button onClick={()=>{if(confirm('Restart from scratch? This clears ALL ZeroOne progress and drafts in this browser.')){resetAllLearningData();location.href=import.meta.env.BASE_URL}}} className="px-3 py-2 rounded-lg border border-red-900 text-red-400 hover:bg-red-950/30 text-xs font-mono">Restart from scratch</button></div></section>
  </div></div>
}
