/**
 * GoDeeper — shown below the Arena for C1-C3 levels.
 * The browser challenges grade pure numpy; the full PyTorch labs live as
 * Colab notebooks in this repo (colab/, generated by scripts/build_colab.py).
 * Colab has torch preinstalled and a free GPU, so "go deeper" is one click.
 */

const REPO = 'bankoti/llm-quest'
const COLAB_COURSES = new Set([1, 2, 3])

interface Props {
  courseId: number
  challengeFile: string  // e.g. "c1/06_attention.py"
}

export function GoDeeper({ courseId, challengeFile }: Props) {
  if (!COLAB_COURSES.has(courseId)) return null
  // Debug levels (90_*) are quest-only exercises with no PyTorch lab.
  if ((challengeFile.split('/').pop() ?? '').startsWith('90_')) return null

  const notebookPath = `colab/${challengeFile.replace(/\.py$/, '.ipynb')}`
  const colabUrl = `https://colab.research.google.com/github/${REPO}/blob/main/${notebookPath}`
  const githubUrl = `https://github.com/${REPO}/blob/main/${notebookPath}`

  return (
    <div className="mt-3 rounded-xl border border-gray-800 bg-gray-900/60 px-4 py-3 flex items-start gap-3">
      <span className="text-lg mt-0.5 shrink-0">🚀</span>
      <div className="flex-1 min-w-0">
        <p className="text-xs font-semibold text-gray-300 mb-0.5">Go Deeper — Full PyTorch Lab</p>
        <p className="text-xs text-gray-500 leading-relaxed mb-2">
          The browser version grades numpy. This same exercise also exists as a
          PyTorch notebook: open it in Google Colab (free, torch preinstalled,
          GPU optional) and solve it with real tensors.
        </p>
        <div className="flex gap-2 flex-wrap">
          <a
            href={colabUrl}
            target="_blank"
            rel="noopener noreferrer"
            className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-amber-600 hover:bg-amber-500 text-white text-xs font-mono font-semibold transition-colors"
          >
            <svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="currentColor">
              <path d="M12 6.5a5.5 5.5 0 1 0 0 11 5.5 5.5 0 0 0 0-11zm0 9a3.5 3.5 0 1 1 0-7 3.5 3.5 0 0 1 0 7zM4.9 8.6a5.5 5.5 0 0 0 0 6.8l1.6-1.2a3.5 3.5 0 0 1 0-4.4L4.9 8.6zm14.2 0-1.6 1.2a3.5 3.5 0 0 1 0 4.4l1.6 1.2a5.5 5.5 0 0 0 0-6.8z"/>
            </svg>
            Open in Colab
          </a>
          <a
            href={githubUrl}
            target="_blank"
            rel="noopener noreferrer"
            className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg border border-gray-700 hover:border-gray-500 text-gray-300 hover:text-white text-xs font-mono transition-colors"
          >
            View notebook →
          </a>
        </div>
      </div>
    </div>
  )
}
