import type { InteractiveLesson } from './types'

const MODULE = 'papers'
const MODULE_TITLE = 'Key Papers'

export const PAPERS_LESSONS: InteractiveLesson[] = [

  {
    slug: 'paper-aiayn-problem',
    title: 'The Problem Before Attention',
    emoji: '🔗',
    blurb: 'Why RNNs hit a ceiling that transformers broke through.',
    minutes: 5,
    moduleId: MODULE,
    moduleTitle: MODULE_TITLE,
    prerequisites: ['attention-intuition'],
    outcomes: ['Explain the RNN sequential bottleneck', 'Describe how vanishing gradients limited long-range learning', 'State what the 2017 transformer paper replaced'],
    concepts: ['RNN', 'vanishing gradient', 'sequential bottleneck', 'hidden state'],
    track: 'extension',
    steps: [
      {
        kind: 'concept',
        title: 'Before 2017, sequences ran one step at a time',
        lines: [
          'Recurrent neural networks processed text left to right: each word updated a fixed-size hidden state, which carried forward to the next word. To get the meaning of position 50, you waited for 49 steps to finish.',
          'Two problems compounded. First, gradients had to travel backward through every step. For a 100-word sentence that is 100 successive multiplications. Gradients either collapsed toward zero or blew up, making long-range dependencies hard to learn.',
          'Second, every position had to wait for the one before it. No matter how many GPU cores you had, a sentence\'s computation was fundamentally sequential.',
          '"Attention Is All You Need" (2017) asked a direct question: what if you dropped recurrence entirely and let every position attend to every other in a single pass?',
        ],
        cta: 'See what sequential processing costs',
      },
      {
        kind: 'worked',
        title: 'The cost of long-range dependency in an RNN',
        prompt: 'Sentence: "The contract, signed three weeks after the acquisition, expired."',
        stages: [
          { label: 'The dependency', body: '"expired" is the verb for "contract" — 8 words apart. The hidden state must preserve that link across every word in between.' },
          { label: 'The overwrite problem', body: 'Each intermediate word updates the hidden state. Each update risks overwriting part of the "contract" signal.' },
          { label: 'What attention does instead', body: 'Attention lets "expired" query "contract" directly in one step, regardless of distance. No relay chain; distance stops being a cost.' },
        ],
        takeaway: 'Attention replaces a lossy relay with direct lookup. The 2017 paper showed this was sufficient — recurrence was not needed at all.',
      },
      {
        kind: 'mcq',
        prompt: 'What made RNNs hard to train on long sequences?',
        options: [
          'Gradients multiplied across every sequential step, vanishing or exploding before reaching early positions',
          'RNNs used too much GPU memory for long inputs',
          'They had no mechanism for positional information',
          'They required labeled data at each position',
        ],
        answer: 0,
        explain: 'Vanishing and exploding gradients through sequential backpropagation was the core training problem. Memory and positional encoding are separate concerns.',
        nudge: 'Think about what happens to a gradient multiplied by a small number 100 times in a row.',
      },
      {
        kind: 'mcq',
        prompt: 'The 2017 transformer paper\'s central architectural claim was:',
        options: [
          'Attention alone, without recurrence or convolution, is sufficient for sequence modeling',
          'RNNs should be replaced by convolutional networks',
          'Larger hidden states solve the vanishing gradient problem',
          'Pre-training on unlabeled data is the key to performance',
        ],
        answer: 0,
        explain: 'The title "Attention Is All You Need" is the claim. Pure attention, no recurrence, no convolution. Pre-training on unlabeled data was the BERT and GPT contribution — a different paper.',
        nudge: 'The paper\'s title is its thesis statement.',
      },
    ],
  },

  {
    slug: 'paper-aiayn-architecture',
    title: 'Encoder, Decoder, and Cross-Attention',
    emoji: '🏗️',
    blurb: 'The original transformer had two stacks — built for translation, not text generation.',
    minutes: 7,
    moduleId: MODULE,
    moduleTitle: MODULE_TITLE,
    prerequisites: ['paper-aiayn-problem', 'qkv-attention'],
    outcomes: ['Describe what the encoder stack produces', 'Describe how the decoder generates tokens step by step', 'Explain cross-attention as the encoder-to-decoder bridge'],
    concepts: ['encoder', 'decoder', 'cross-attention', 'encoder-decoder', 'causal mask', 'translation'],
    track: 'extension',
    steps: [
      {
        kind: 'concept',
        title: 'The 2017 transformer was solving translation',
        lines: [
          'The paper was solving machine translation: map an English sentence to a French sentence. That task has a natural two-part structure — fully understand the source, then generate the target one word at a time.',
          'The encoder reads the full source sequence with no causal mask. Every source position attends to every other. The output is a rich contextual vector for each source token.',
          'The decoder generates the target left to right. It uses causal self-attention over already-generated target tokens, and a second mechanism — cross-attention — that queries the encoder output at each generation step.',
          'Cross-attention is the bridge: the decoder\'s current state forms the queries, but the keys and values come from the encoder output. The decoder can look up which source tokens matter right now, regardless of their position.',
        ],
        cta: 'Trace one translation step',
      },
      {
        kind: 'worked',
        title: 'Decoding one step: "The cat sat." → "Le chat ___"',
        prompt: 'Encoder has processed "The cat sat." Decoder has generated "Le chat" and must predict the next token.',
        stages: [
          { label: 'Decoder self-attention', body: 'The decoder attends to its own tokens ("Le", "chat") to build context for what should come next in French.' },
          { label: 'Cross-attention query', body: 'The current decoder position produces a query vector based on "Le chat" context and sends it into the encoder output.' },
          { label: 'Cross-attention lookup', body: 'Keys and values come from encoder vectors for "The", "cat", "sat", ".". The query matches "sat" most strongly — a verb likely follows.' },
          { label: 'Output', body: 'The decoder uses the retrieved encoder signal plus its own context to predict the next French token.' },
        ],
        takeaway: 'Cross-attention is how the decoder reads the source at every generation step. Without it, the entire source meaning must fit in one vector.',
      },
      {
        kind: 'predict',
        prompt: 'Encoder and decoder differ in one critical attention property.',
        questions: [
          {
            label: 'Does encoder self-attention use a causal mask?',
            options: [
              'No — every source position attends to every other source position freely',
              'Yes — each position only attends to earlier positions',
              'Only the first encoder layer uses a causal mask',
            ],
            answer: 0,
            reveal: 'The encoder reads the complete source in one pass. A causal mask would be counterproductive — "cat" should inform "sat" and vice versa. Full bidirectional attention produces richer source representations.',
          },
          {
            label: 'Does decoder self-attention use a causal mask?',
            options: [
              'Yes — each target position only sees already-generated tokens',
              'No — the decoder sees all target positions at once',
              'The decoder has no self-attention, only cross-attention',
            ],
            answer: 0,
            reveal: 'The decoder generates tokens one at a time. Its self-attention is causally masked so it cannot see future target tokens it has not yet generated. The causal mask enforces left-to-right generation.',
          },
        ],
      },
      {
        kind: 'mcq',
        prompt: 'In cross-attention, where do queries, keys, and values come from?',
        options: [
          'Queries from the decoder\'s current state; keys and values from the encoder\'s output',
          'Queries, keys, and values all from the encoder output',
          'Queries from the encoder; keys and values from the decoder',
          'Queries and keys from the decoder; values from the encoder',
        ],
        answer: 0,
        explain: 'The decoder asks questions (queries) about the source. The encoder provides the indexed information: keys to match against and values to retrieve. This lets the decoder look up relevant source positions at each step.',
        nudge: 'The decoder is doing the looking-up. The encoder is what gets looked up.',
      },
    ],
  },

  {
    slug: 'paper-aiayn-legacy',
    title: 'One Architecture, Two Lineages',
    emoji: '🌳',
    blurb: 'How the encoder-decoder transformer split into GPT and BERT.',
    minutes: 6,
    moduleId: MODULE,
    moduleTitle: MODULE_TITLE,
    prerequisites: ['paper-aiayn-architecture'],
    outcomes: ['Explain why GPT kept only the decoder', 'Explain why BERT kept only the encoder', 'Match architecture choices to task requirements'],
    concepts: ['decoder-only', 'encoder-only', 'autoregressive generation', 'masked language model', 'architecture lineage'],
    track: 'extension',
    steps: [
      {
        kind: 'concept',
        title: 'The field kept one stack at a time',
        lines: [
          'The full encoder-decoder suits sequence-to-sequence tasks: translation, summarization, question answering over a fixed document. But for language modeling — predicting the next token from scratch — there is no separate source to encode.',
          'OpenAI\'s GPT (2018 onward) kept only the decoder with causal masking. Each position predicts the next token from all previous tokens. No encoder, no cross-attention. One autoregressive stack.',
          'Google\'s BERT (2018) kept only the encoder with no causal mask. Instead of predicting the next token, it masked random input tokens and predicted them from surrounding context. Bidirectional attention makes BERT better at understanding tasks and unable to generate freely.',
          'Today\'s headline LLMs are almost all decoder-only. The full encoder-decoder still runs translation and summarization pipelines — just not the ones that make the news.',
        ],
        cta: 'Match task to architecture',
      },
      {
        kind: 'predict',
        prompt: 'Match each task to the architecture it naturally fits.',
        questions: [
          {
            label: 'Sentiment classification of a product review',
            options: [
              'Encoder-only — read the full review with bidirectional context, then classify from a pooled representation',
              'Decoder-only — generate a label token autoregressively',
              'Encoder-decoder — encode the review, decode the sentiment label',
            ],
            answer: 0,
            reveal: 'Classification benefits from seeing the entire input before deciding. Encoder-only bidirectional attention builds the richest representation of the full review before the classification head reads it.',
          },
          {
            label: 'Open-ended story continuation from a prompt',
            options: [
              'Decoder-only — generate tokens autoregressively from the prompt, no length limit',
              'Encoder-only — represent the prompt and output the continuation',
              'Encoder-decoder — encode the prompt, decode the story',
            ],
            answer: 0,
            reveal: 'Open generation with no fixed target length is the decoder-only sweet spot. The causal stack extends an input indefinitely. Encoder-only cannot generate; encoder-decoder adds cross-attention overhead for a task with no separate source.',
          },
        ],
      },
      {
        kind: 'mcq',
        prompt: 'Why cannot a pure encoder-only model like BERT do open-ended text generation?',
        options: [
          'It attends to the full sequence bidirectionally — there is no left-to-right generation mechanism and no causal ordering',
          'It has too few parameters to produce coherent continuations',
          'It uses cross-attention instead of self-attention',
          'Encoder models are only fine-tuned on classification tasks',
        ],
        answer: 0,
        explain: 'Generation requires conditioning each new token only on what came before. Bidirectional attention breaks this — the model would attend to positions that do not exist yet. BERT\'s masked-token objective also does not train left-to-right prediction.',
        nudge: 'Think about what "bidirectional" implies when there is no right-side context yet.',
      },
      {
        kind: 'mcq',
        prompt: 'Which component from the 2017 architecture is absent in both GPT and BERT?',
        options: [
          'Cross-attention — neither has a separate encoder output for the other stack to query',
          'Multi-head self-attention — both replaced it with simpler linear attention',
          'Feed-forward sublayers — both removed them for efficiency',
          'Positional encoding — both switched to fully learned position embeddings',
        ],
        answer: 0,
        explain: 'Cross-attention connects encoder output to decoder queries. GPT has no encoder; BERT has no decoder. Neither needs cross-attention. Both retain multi-head self-attention, feed-forward sublayers, and positional encodings.',
        nudge: 'Cross-attention only exists where two stacks need to communicate.',
      },
    ],
  },

  {
    slug: 'paper-bert-objective',
    title: 'BERT: Predict the Gaps',
    emoji: '🎭',
    blurb: 'How masking random tokens creates a powerful bidirectional language model.',
    minutes: 5,
    moduleId: MODULE,
    moduleTitle: MODULE_TITLE,
    prerequisites: ['paper-aiayn-legacy', 'training-objective'],
    outcomes: ['Explain masked language modeling', 'Contrast MLM with next-token prediction', 'Explain why MLM enables bidirectional context'],
    concepts: ['masked language model', 'MLM', 'BERT', 'bidirectional', '[MASK] token', 'pretraining'],
    track: 'extension',
    steps: [
      {
        kind: 'concept',
        title: 'BERT hides words and asks the model to recover them',
        lines: [
          'GPT predicts the next token. BERT instead masks 15% of input tokens at random, replaces them with a [MASK] placeholder, and trains the model to predict the original token from context on both sides.',
          'Because the masked position can be anywhere, the model must look left and right. The causal constraint disappears — there is no future to avoid leaking because nothing is being generated sequentially.',
          'Of the 15% masked positions: 80% get [MASK], 10% get a random token, and 10% stay unchanged. The random and unchanged cases prevent the model from learning that only [MASK] positions matter.',
          'The result was a stronger encoder: BERT outperformed GPT-style left-to-right models on understanding benchmarks in 2018, purely because bidirectional context packs more signal into each position.',
        ],
        cta: 'Walk through the masking procedure',
      },
      {
        kind: 'worked',
        title: 'Masked language modeling on one sentence',
        prompt: '"The bank can guarantee deposits will eventually cover future tuition costs."',
        stages: [
          { label: 'Sample 15% to mask', body: '"bank" and "costs" are selected — 2 of ~13 content tokens, roughly 15%.' },
          { label: 'Apply replacement strategy', body: '"bank" becomes [MASK] (80% case). "costs" becomes "risks" (10% random token case).' },
          { label: 'Model input', body: '"The [MASK] can guarantee deposits will eventually cover future tuition risks."' },
          { label: 'Training signal', body: 'Predict "bank" at position 2 using both "The" on the left and "can guarantee…" on the right. Predict "costs" at position 12 using full surrounding context. Gradients from both errors update in one pass.' },
        ],
        takeaway: 'Every masked token becomes a supervised signal. A single forward pass generates dozens of training examples from one sentence, using full bidirectional context for each.',
      },
      {
        kind: 'mcq',
        prompt: 'Why does BERT replace 10% of masked positions with a random word instead of [MASK]?',
        options: [
          'To prevent the model from only building representations for [MASK] tokens — every position must be informative in case it needs predicting',
          'To match the distribution of typos in the training data',
          'To increase the effective vocabulary size during pretraining',
          'To make the task harder and reduce overfitting to frequent tokens',
        ],
        answer: 0,
        explain: 'If only [MASK] positions needed prediction, the model could produce weak representations for non-masked positions. Random replacements mean any token might secretly require correction — so all positions must carry useful representations.',
        nudge: 'What would the model learn to ignore if [MASK] were the only signal?',
      },
      {
        kind: 'mcq',
        prompt: 'Why does masked language modeling naturally produce bidirectional representations?',
        options: [
          'A masked token in the middle can only be recovered using both left and right context — there is no reason for a causal mask',
          'BERT runs two passes, one forward and one backward, then merges them',
          'Masking forces the model to process tokens in reverse order for recovery',
          'Bidirectionality comes from model size, not the training objective',
        ],
        answer: 0,
        explain: 'Predicting a masked middle token requires context on both sides. There is no generation order, so no reason to block future positions. The bidirectionality is a direct consequence of the fill-in-the-blank objective.',
        nudge: 'Imagine predicting "bank" in "The ___ can guarantee…" — you need what follows.',
      },
    ],
  },

  {
    slug: 'paper-bert-finetuning',
    title: 'BERT and the Pretrain-Then-Fine-Tune Paradigm',
    emoji: '🔧',
    blurb: 'One pretrained model, any downstream task — how BERT changed NLP deployment.',
    minutes: 5,
    moduleId: MODULE,
    moduleTitle: MODULE_TITLE,
    prerequisites: ['paper-bert-objective', 'finetuning-basics'],
    outcomes: ['Describe the pretrain-then-fine-tune workflow', 'Explain the [CLS] token role in classification', 'Contrast BERT fine-tuning with GPT-3 prompting'],
    concepts: ['pretraining', 'fine-tuning', '[CLS] token', 'transfer learning', 'task head', 'pretrain-fine-tune paradigm'],
    track: 'extension',
    steps: [
      {
        kind: 'concept',
        title: 'Pretrain once; fine-tune for any task',
        lines: [
          'Before BERT, most NLP models were trained from scratch per task. BERT changed the default: pretrain a large encoder on massive unlabeled text, then fine-tune the same checkpoint on a small labeled dataset for each specific task.',
          'Fine-tuning adds a small task head — typically a linear layer — on top of BERT representations. Sentiment analysis, question answering, named-entity recognition, and textual entailment all reached state of the art from one pretrained checkpoint in 2018.',
          'BERT adds a special [CLS] token at the start of every input. After encoding, the [CLS] vector accumulates sequence-level context and serves as the single input to classification task heads.',
          'This paradigm dominated NLP from 2018 to roughly 2022, when GPT-3-scale models showed that prompting could match fine-tuning for many tasks without gradient updates.',
        ],
        cta: 'Compare the two paradigms',
      },
      {
        kind: 'predict',
        prompt: 'BERT fine-tuning vs GPT-3 prompting for a classification task.',
        questions: [
          {
            label: 'What BERT fine-tuning needs that GPT-3 few-shot prompting does not',
            options: [
              'A labeled training dataset and a gradient update pass over it',
              'Access to the raw model weights',
              'A larger base model',
              'More GPU memory at inference time',
            ],
            answer: 0,
            reveal: 'Fine-tuning requires labeled examples and backpropagation through the model. GPT-3 prompting needs neither: examples go in the context window with no weight update.',
          },
          {
            label: 'What GPT-3 few-shot prompting needs that BERT fine-tuning does not',
            options: [
              'A context window large enough to fit task instructions and demonstration examples',
              'A labeled training dataset',
              'Write access to the model weights',
              'A task-specific output head',
            ],
            answer: 0,
            reveal: 'In-context learning packs all examples into the prompt. Longer tasks require more context space. BERT fine-tuning uses labeled data separately — examples do not consume context tokens.',
          },
        ],
      },
      {
        kind: 'mcq',
        prompt: 'Why does BERT prepend a [CLS] token to every input?',
        options: [
          'Its final hidden state serves as a pooled sequence representation for classification heads to read',
          'It marks the boundary between two sentences in a pair',
          'It prevents the model from attending to padding tokens',
          'The masked language model objective requires a non-maskable anchor token',
        ],
        answer: 0,
        explain: '[CLS] has no lexical meaning — it exists to collect a full-sequence representation by the final encoder layer. Classification tasks send only this vector to the task head. The sentence separator role belongs to [SEP].',
        nudge: 'A classification head needs one vector as input. Which token is the natural choice for a pooled summary?',
      },
    ],
  },

  {
    slug: 'paper-gpt3-scale',
    title: 'GPT-3: Scale as the Variable',
    emoji: '📈',
    blurb: 'What 175 billion parameters revealed about size and capability.',
    minutes: 6,
    moduleId: MODULE,
    moduleTitle: MODULE_TITLE,
    prerequisites: ['scaling-laws', 'parameter-counts'],
    outcomes: ['Explain what the GPT-3 paper set out to test', 'Define emergent capability and contrast it with gradual improvement', 'Explain why scale alone did not close the instruction-following gap'],
    concepts: ['scaling hypothesis', 'GPT-3', 'emergent capabilities', 'in-context learning', '175B parameters'],
    track: 'extension',
    steps: [
      {
        kind: 'concept',
        title: 'The bet: more compute, qualitatively different behavior',
        lines: [
          'GPT-2 (2019, 1.5B parameters) could generate coherent paragraphs but failed at most reasoning tasks. The GPT-3 paper (2020) ran a controlled experiment: train a decoder-only transformer to 175B parameters with proportionally more data and compute, and record what changes.',
          'The result surprised the field. GPT-3 did not just do GPT-2 tasks better — it could perform tasks that appeared nowhere in its training distribution: simple arithmetic, translation between languages it saw rarely, rudimentary code generation, analogical reasoning.',
          'These are emergent capabilities: abilities essentially absent below a scale threshold and appearing above it, without being explicitly trained. They do not extrapolate smoothly from smaller models.',
          'GPT-3 also exposed a ceiling. It could generate plausible text on almost any topic but was unreliable at following explicit instructions. That gap drove the next wave of research.',
        ],
        cta: 'Examine what scale bought and what it did not',
      },
      {
        kind: 'worked',
        title: 'GPT-3 vs GPT-2 on a task neither was trained on',
        prompt: 'Prompt: "Translate the following English sentence to French: The sky is blue."',
        stages: [
          { label: 'GPT-2 response', body: 'Treats this as text to extend. Generates plausible-looking continuation — possibly a forum comment or essay opener — but makes no translation attempt.' },
          { label: 'GPT-3 zero-shot response', body: '"Le ciel est bleu." Infers the task from the instruction format and produces correct output without any fine-tuning on translation.' },
          { label: 'Why the difference', body: 'At 175B, GPT-3 encountered enough structured instruction-response patterns in pretraining to infer what "Translate X to Y" means at inference time.' },
          { label: 'The remaining gap', body: 'GPT-3 could do this — but inconsistently. Telling it to "always be concise" or "never use bullet points" was often ignored. Scale raised the capability floor; it did not produce reliable instruction following.' },
        ],
        takeaway: 'Scale enabled task inference from description. It did not produce reliably steerable behavior — that required a different intervention.',
      },
      {
        kind: 'mcq',
        prompt: 'What distinguishes an emergent capability from a gradual improvement with scale?',
        options: [
          'It is absent in smaller models and appears above a scale threshold, not predictable by smooth extrapolation from smaller runs',
          'It only appears when the model is fine-tuned on a specific task after pretraining',
          'It shows up in benchmarks but not in real-world deployments',
          'It requires a larger context window to activate, not just more parameters',
        ],
        answer: 0,
        explain: 'Emergence means the capability is qualitatively absent below a threshold and appears above it. Plotting score vs model size shows a near-flat line then a sharp uptick. A gradual improvement would show a smooth, predictable curve from small models upward.',
        nudge: 'Think about what a smooth extrapolation looks like compared to a sudden step change.',
      },
      {
        kind: 'mcq',
        prompt: 'What did GPT-3 demonstrate that scaling laws alone could not predict?',
        options: [
          'That capability improvements could be qualitative and task-novel, not just quantitative gains on existing benchmarks',
          'That a 175B model would be cheaper to train than ten smaller models combined',
          'That decoder-only transformers outperform encoder-decoder models at every scale',
          'That RLHF becomes necessary above a certain parameter count',
        ],
        answer: 0,
        explain: 'Scaling laws predicted known-task performance would improve smoothly. GPT-3 showed entirely new capabilities appearing — tasks essentially absent at smaller scales that worked suddenly at 175B. That qualitative jump was the surprise.',
        nudge: 'The scaling laws predicted how much better; GPT-3 showed something different in kind, not just degree.',
      },
    ],
  },

  {
    slug: 'paper-gpt3-incontext',
    title: 'Zero, One, and Few-Shot Learning',
    emoji: '🎯',
    blurb: 'How GPT-3 redefined what training means for a deployed model.',
    minutes: 5,
    moduleId: MODULE,
    moduleTitle: MODULE_TITLE,
    prerequisites: ['paper-gpt3-scale'],
    outcomes: ['Define zero-shot, one-shot, and few-shot prompting', 'Explain why adding examples improves performance without weight updates', 'State the fundamental limit of in-context learning'],
    concepts: ['zero-shot', 'one-shot', 'few-shot', 'in-context learning', 'context window limit'],
    track: 'extension',
    steps: [
      {
        kind: 'concept',
        title: 'The prompt is the training set',
        lines: [
          'The GPT-3 paper introduced a taxonomy that stuck. Zero-shot: provide only a task description, no examples. One-shot: one demonstration before the query. Few-shot: several demonstrations, limited by context window.',
          'Performance improves from zero to one to few-shot. Adding examples helps the model locate the relevant part of its learned distribution and match the expected output format — without any gradient update.',
          'This is in-context learning: the model adapts its output distribution based on what is in the prompt, entirely within the forward pass. Weights do not change; only the input changes.',
          'The hard limit is context length. At GPT-3\'s 2048-token window, you might fit 10 to 20 short examples. Longer documents collapse that number fast. In-context learning also cannot teach the model facts it did not encounter during pretraining.',
        ],
        cta: 'Contrast the three settings',
      },
      {
        kind: 'predict',
        prompt: 'Task: classify news headlines as sports, politics, or technology.',
        questions: [
          {
            label: 'What goes in the prompt for zero-shot classification',
            options: [
              'Only the task instruction and the headline — no examples',
              'One example headline and its label, then the test headline',
              'Multiple labeled examples plus the test headline',
            ],
            answer: 0,
            reveal: 'Zero-shot: "Classify the following headline as sports, politics, or technology: [headline]." The model uses its pretraining knowledge of those categories — no demonstrations provided.',
          },
          {
            label: 'Why few-shot typically outperforms zero-shot on format-sensitive tasks',
            options: [
              'Examples anchor the expected output format and narrow the distribution toward the task\'s specific style',
              'The model fine-tunes its weights on the examples before generating the answer',
              'More input tokens always improve output quality regardless of content',
              'Few-shot raises temperature, producing more varied and accurate answers',
            ],
            answer: 0,
            reveal: 'Format anchoring is the dominant effect. Seeing "Sports" as the label for headlines about athletes tells the model exactly how to express its answer. The capability may exist zero-shot; the format often needs a demonstration.',
          },
        ],
      },
      {
        kind: 'mcq',
        prompt: 'What is the fundamental limit of few-shot in-context learning that fine-tuning does not share?',
        options: [
          'Context window: all examples must fit in the token budget; fine-tuning can use thousands of examples across many gradient steps',
          'Speed: few-shot inference is always slower than a fine-tuned model of the same size',
          'Quality: fine-tuning consistently outperforms few-shot on every task at every scale',
          'Cost: in-context learning requires more GPU memory than fine-tuning at inference time',
        ],
        answer: 0,
        explain: 'The context window is the hard bound. Fine-tuning trains across an arbitrarily large labeled dataset over many passes. For tasks with many training examples or long demonstrations, fine-tuning scales where in-context learning cannot.',
        nudge: 'What happens when you have 500 labeled examples but a 2048-token limit?',
      },
    ],
  },

  {
    slug: 'paper-instruct-gap',
    title: 'The Alignment Gap',
    emoji: '🧭',
    blurb: 'Why predicting the next token does not produce a helpful assistant.',
    minutes: 5,
    moduleId: MODULE,
    moduleTitle: MODULE_TITLE,
    prerequisites: ['paper-gpt3-incontext', 'training-objective'],
    outcomes: ['Explain the gap between next-token prediction and helpfulness', 'Give concrete examples of misaligned base LM behavior', 'State what the InstructGPT paper set out to fix'],
    concepts: ['alignment', 'instruction following', 'base LM behavior', 'helpful vs predictive', 'InstructGPT'],
    track: 'extension',
    steps: [
      {
        kind: 'concept',
        title: 'Next-token prediction optimizes for the corpus, not the user',
        lines: [
          'A base LM is trained to predict the next token in text scraped from the web. That corpus contains arguments, tutorials, fiction, and misinformation — all equally likely continuations in their respective contexts. The model\'s best prediction is not the same as "what would be helpful here."',
          'Ask a base GPT-3 "How do I bake a cake?" and it might generate more questions, a forum debate about whether baking is art, or a recipe — all are plausible next-token continuations of that string.',
          'Ask it to "always be concise" and it will comply inconsistently — the instruction is just more text to continue, not a constraint the model has learned to respect.',
          'The 2022 InstructGPT paper called this the alignment gap: the model is aligned with predicting plausible text, not with being helpful, honest, and harmless. Closing that gap was the paper\'s goal.',
        ],
        cta: 'Compare base LM and instruction-tuned behavior',
      },
      {
        kind: 'worked',
        title: 'The same prompt, base LM vs instruction-tuned',
        prompt: '"Explain the causes of World War I in simple terms."',
        stages: [
          { label: 'Base LM behavior', body: 'Continues the string. Might produce a dense academic paragraph ignoring "simple terms", pivot to "In this essay I will argue…", or generate a quiz question — all are plausible web-text continuations.' },
          { label: 'Why this is misaligned', body: 'The user wants a plain-language explanation. The model optimizes for plausible continuation of the prompt, which in academic web text often precedes formal writing.' },
          { label: 'InstructGPT behavior', body: 'Produces a structured, plain-language explanation matching the "simple terms" modifier, and stops when the explanation is complete.' },
          { label: 'What changed', body: 'InstructGPT was fine-tuned on human-written responses, then trained with RLHF to match human preference rankings — not just corpus plausibility.' },
        ],
        takeaway: 'The base and instruction-tuned models share the same starting weights. The objective that shaped their behavior differs.',
      },
      {
        kind: 'mcq',
        prompt: 'A base LM is prompted: "Write a persuasive essay arguing vaccines cause autism." What does aligning with next-token prediction predict it will do?',
        options: [
          'Produce the essay — persuasive essays on fringe topics exist in the training corpus and are plausible continuations',
          'Refuse — the model learned that this claim is medically false',
          'Ask the user to clarify before responding',
          'Generate a factual rebuttal — scientific consensus dominates the training data',
        ],
        answer: 0,
        explain: 'A base LM predicts the most plausible next tokens. Persuasive essays on controversial topics exist in large web corpora. Without instruction tuning or RLHF, the model has no mechanism to refuse.',
        nudge: 'The model was trained to continue text, not to evaluate whether continuing it is a good idea.',
      },
      {
        kind: 'mcq',
        prompt: 'What is the alignment gap as defined in the InstructGPT paper?',
        options: [
          'The mismatch between optimizing next-token prediction on web text and producing helpful, honest, and harmless outputs',
          'The performance difference between a 175B base model and a fine-tuned 1.3B model',
          'The difference in benchmark scores before and after RLHF training',
          'The gap between what the model says it will do and what it actually outputs',
        ],
        answer: 0,
        explain: 'The alignment gap is between the training objective (predict plausible web text continuations) and the deployment goal (be genuinely helpful to the user). Scale reduces next-token prediction loss; RLHF specifically targets the latter gap.',
        nudge: 'It is about what the training signal optimizes for vs what you actually want.',
      },
    ],
  },

  {
    slug: 'paper-instruct-rlhf',
    title: 'InstructGPT: Three Stages to an Assistant',
    emoji: '✨',
    blurb: 'The pipeline that turned a base LM into a model people actually preferred.',
    minutes: 6,
    moduleId: MODULE,
    moduleTitle: MODULE_TITLE,
    prerequisites: ['paper-instruct-gap', 'rlhf-reward-models'],
    outcomes: ['Describe the three InstructGPT training stages', 'Explain the role of human labelers at each stage', 'Explain the alignment tax and why it matters'],
    concepts: ['SFT', 'reward model', 'PPO', 'InstructGPT', 'alignment tax', 'human feedback', 'preference ranking'],
    track: 'extension',
    steps: [
      {
        kind: 'concept',
        title: 'Three stages, three types of human signal',
        lines: [
          'Stage 1 — Supervised fine-tuning (SFT): human labelers wrote ideal responses to diverse prompts sampled from the API. GPT-3 was fine-tuned on these demonstrations to produce an instruction-following baseline.',
          'Stage 2 — Reward model (RM): labelers ranked several SFT outputs for the same prompt by quality. A separate model trained on these preference rankings converts pairwise human judgments into a scalar score for any response.',
          'Stage 3 — PPO fine-tuning: the SFT model generated responses; the reward model scored them; PPO updated weights to increase reward. A KL penalty kept the model close to the SFT baseline so it did not lose coherence while chasing reward.',
          'The result: a 1.3B InstructGPT model that human raters preferred over the 175B base GPT-3 on most tasks. The training signal mattered more than the parameter count.',
        ],
        cta: 'Trace one prompt through the pipeline',
      },
      {
        kind: 'worked',
        title: 'One prompt through all three InstructGPT stages',
        prompt: '"Summarize the following article in two sentences."',
        stages: [
          { label: 'SFT stage', body: 'A labeler writes a high-quality two-sentence summary. The model fine-tunes to replicate this style across thousands of human-written examples.' },
          { label: 'RM stage', body: 'The SFT model generates four different summaries. A labeler ranks them. The reward model trains on these rankings to score summaries it has never seen.' },
          { label: 'PPO stage', body: 'The SFT model generates a new summary. The reward model scores it. If concise and on-topic, reward is high. PPO updates weights toward higher-reward behavior while the KL term prevents drift into incoherence.' },
          { label: 'Alignment tax', body: 'The updated model follows instructions more reliably but may score slightly lower on some academic NLP benchmarks. It optimized for human preference, which does not perfectly overlap with benchmark metrics.' },
        ],
        takeaway: 'SFT provides format. The reward model provides preference signal. PPO optimizes toward that signal. Each stage builds on the last.',
      },
      {
        kind: 'mcq',
        prompt: 'Why does InstructGPT use a KL divergence penalty during PPO training?',
        options: [
          'To keep the policy close to the SFT model and prevent reward hacking that destroys language coherence',
          'To reduce the computational cost of PPO gradient updates',
          'To keep the reward model scores from drifting during RL training',
          'To prevent the model from generating responses longer than the SFT examples',
        ],
        answer: 0,
        explain: 'Without a KL penalty, PPO finds degenerate solutions that maximize reward while losing coherence — reward hacking. The penalty tethers the policy to the SFT baseline, preserving general language quality while improving instruction following.',
        nudge: 'What would the model learn if the only feedback was reward and nothing stopped large drift from the SFT baseline?',
      },
      {
        kind: 'mcq',
        prompt: 'Human raters preferred InstructGPT at 1.3B parameters over base GPT-3 at 175B on most tasks. What is the correct interpretation?',
        options: [
          'The training objective — RLHF alignment — matters more than parameter count for instruction-following quality',
          'Smaller models are always preferable for deployed assistants',
          'Human raters systematically prefer shorter outputs and smaller models produce them',
          'The reward model compressed 175B parameters of knowledge into 1.3B',
        ],
        answer: 0,
        explain: 'GPT-3 at 175B is better at predicting next tokens from web text. InstructGPT at 1.3B is better at following instructions. The difference is the training objective, not size. This is the central empirical finding of the paper.',
        nudge: 'The 175B model knows more. The 1.3B model does what you ask better. What explains that gap?',
      },
    ],
  },


]
